### ISSUE TITLE
Firebase Melebihi kuota limit

### ISSUE THREAD

**Issue by irsyaadbp** [bachors/Al-Quran-ID-API#3]
halo, apinya sepertinya sudah mencapai limit firebase sehingga sudah tidak bisa diakses, apa bisa diperbaiki? atau mungkin bisa berbagi data sehingga saya bisa membangun api saya sendiri

**Comment by iniakunhuda** [comment]
halo min, mungkin saya bisa bantu support agar APInya bisa up lagi?

**Comment by bachors** [comment]
Sekarang tersedia data versi offlinenya ditambah perbaikan di bagian link audio, dimana di versi onlinenya link audio belum diperbaiki. https://github.com/bachors/Al-Quran-ID-API/blob/master/offline/data.json
